# ----
# Site

title: Aarav Batra
url: "https://recruit.aaravbatra.me"
show_full_navigation: true

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: Aarav Batra's Recruiting Profile
author:
  name: Aarav Batra
  email: aaravbatra@duck.com
  twitter: aaravbatra_56
  instagram: aaravbatra_56
social:
  name: Aarav Batra
  links:
    - https://recruit.aaravbatra.me
    - https://www.aaravbatra.me
    - https://links.aaravbatra.me
    - https://www.hudl.com/profile/18010632/Aarav-Batra
    - https://x.com/aaravbatra_56
    - https://www.instagram.com/aaravbatra_56/
    - https://www.linkedin.com/in/aarav-batra-a0abaa2a4/

# -----
# Build

timezone: ETC/UTC

permalink: pretty

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

collections:
  docs:
    title: Documentation
    permalink: /:path/
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      path: ""
      type: "docs"
    values:
      seo:
        type: Article
      _comments:
        category: Group navigation links with this field
        order: Used to sort links in the navigation
      _options:
        content:
          width: 800
          height: 2000
  -
    scope:
      path: ""
      type: "posts"
    values:
      _comments:
        type: Marks the impact of this release

types:
  - minor
  - major
